### ISSUE TITLE
Content: Concourse - Example Configurations

### ISSUE THREAD

**Issue by ekultails** [vmware-tanzu/tanzu-dev-portal#1126]
## Summary of content

A list of different common configurations for the Concourse Helm chart including:

- Container registry proxy
- Initial user creation
- Persistent storage
- Remote PostgreSQL database
- Custom certificate authorities (CAs)

## Summary of audiences

Developers and administrators deploying and managing Concourse.

## Level of content

Level of content as it pertains to the topic proposed
- [x] 101: "Awareness / Exploration"
- [x] 201: "Prototyping / Deploying"
- [ ] 301: "Scaling
- [ ] Content Series: To include multiple levels of content (Note: Series pieces should either be able to be consumed independently, or very explicit in the title, and with links in the body of the content that they are part of a series)

**Comment by ekultails** [comment]
Once I finish https://github.com/vmware-tanzu/tanzu-dev-portal/issues/1105 I will circle back to this new issue. You folks can go ahead and assign me to this one.

**Comment by ekultails** [comment]
Other ideas to add:

- Ingress
- Ingress with TLS certificates

**Comment by ekultails** [comment]
Efficient copy-on-write storage. Use driver `detect` (recommended) OR explicitly define the driver `btrfs` or `overlay`.

```
---
concourse:
  worker:
    baggageclaim:
      driver: detect
```

**Comment by ekultails** [comment]
Disable persistent storage (for testing purposes):

```
---
persistence:
  enabled: false
postgresql:
  persistence:
    enabled: false
```

**Comment by ekultails** [comment]
TLS certificate with cert-manager:

```
---
web:
  ingress:
    enabled: true
    hosts:
      - concourse.example.com
    annotations:
      cert-manager.io/cluster-issuer: <CLUSTERISSUER>
    tls:
      - hosts:
          - concourse.example.com
        secretName: cert-concourse-web
```

**Comment by ekultails** [comment]
Ingress without a TLS certificate. Not recommended as Concourse web hosts will forward the login page to HTTPS for security reasons which will not work in this scenario.

```
---
web:
  ingress:
    enabled: true
    hosts:
      - concourse.example.com
```

**Comment by ekultails** [comment]
The Concourse Helm chart does not natively expose a container registry proxy variable. Instead, we can manually modify the image name (there is only one singular "concourse" image that is used from the "concourse" project in Docker Hub) to have the proxy identified in it.


```
---
image: <CONTAINER_REGISTRY_PROXY>/concourse/concourse
```

```
---
image: harbor.example.com:443/concourse/concourse
```

**Comment by ekultails** [comment]
Persistent storage enabled:

```
---
persistence:
  worker:
    storageClass: <STORAGECLASS>
postgresql:
  persistence:
    storageClass: <STORAGECLASS>
```

**Comment by ekultails** [comment]
Remote PostgreSQL.

Syntax:

```
---
concourse:
  web:
    postgres:
      host: <POTSGRESQL_HOST>
      database: <POTSGRESQL_DATABASE>
secrets:
  postgresUser: <POSTGRESQL_USERNAME>
  postgresPassword: <POSTGRESQL_PASSWORD>
postgresql:
  enabled: false
```

Example (assumes the [Bitnami Helm chart for PostgreSQL](https://github.com/bitnami/charts/tree/master/bitnami/postgresql) was used to deploy it locally in the "concourse" namespace):

```
---
concourse:
  web:
    postgres:
      host: postgresql.concourse.svc.cluster.local
      database: postgres
secrets:
  postgresUser: postgres
  postgresPassword: postgres
postgresql:
  enabled: false
```
